name: Check Terraform Code Formatting

on:
  pull_request:
    branches:
      - main
    
jobs:
  terraform:
    name: "Run terraform fmt"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt
        run: terraform fmt -check -recursive